---
apiVersion: v1
kind: Service
metadata:
  name: unmount-gpu-monitoring
  labels:
    app: unmount-gpu-monitoring
spec:
  ports:
  - name: "unmount-gpu-monitoring"
    port: 2020
  selector:
    app: unmount-gpu-monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unmount-gpu-monitoring
spec:
  template:
    metadata:
      labels:
        app: unmount-gpu-monitoring
    spec:
      containers:
      - name: unmount-gpu-monitoring
        image: hyj2508/2u-unmount-gpu-memory:latest
        ports:
        - containerPort: 2020

